Repository vacatius/mobile-app, pull requests merged in 2021-05, with the labels that each got.

#54 Feature/8 view and edit activity
  .idea/codeStyles/Project.xml
  App.tsx
  package-lock.json
  package.json
  src/components/ActivityCard/ActivityCard.tsx
  src/components/ActivityGroup.tsx
  src/components/svg/SvgStrandedTraveller.tsx
  src/screens/Itinerary/TripItinerary.tsx
  src/screens/ViewAddEditActivity/ViewAddEditActivity.tsx
  src/screens/ViewAddEditActivity/createActivityMutation.gql
  src/screens/ViewAddEditActivity/getActivityQuery.gql
  src/screens/ViewAddEditActivity/removeActivityMutation.gql
  src/screens/ViewAddEditActivity/types/createActivityMutation.ts
  src/screens/ViewAddEditActivity/types/getActivityQuery.ts
  src/screens/ViewAddEditActivity/types/removeActivityMutation.ts
  src/screens/ViewAddEditActivity/types/updateActivityMutation.ts
  src/screens/ViewAddEditActivity/updateActivityMutation.gql
  src/services/i18n.ts
  src/types/RootStackParamList.ts
  src/types/Routes.ts
  used-libs.md
Labels: initial app concept

#60 Implement navbar for View/Edit Trip Details screen
  App.tsx
  package-lock.json
  package.json
  src/routes/TripTabs.tsx
  src/screens/Itinerary/TripItinerary.tsx
  src/screens/TripSettings/TripSettings.tsx
  src/screens/TripsDashboard/TripsDashboard.tsx
  src/types/RootStackParamList.ts
  src/types/Routes.ts
  src/types/TripTabParamList.ts
Labels: initial app concept

#65 Bug/59 cant press stuff
  src/screens/AddEditActivityGroup/AddEditActivityGroupScreen.tsx
  src/screens/AddTrip/AddTrip.tsx
  src/screens/Login/Login.tsx
  src/screens/Register/Register.tsx
  src/screens/ViewAddEditActivity/ViewAddEditActivity.tsx
Labels: bug

#74 Fix versioning issues
  App.tsx
  package-lock.json
  package.json
  src/screens/AddEditActivityGroup/AddEditActivityGroupScreen.tsx
  src/screens/ViewAddEditActivity/ViewAddEditActivity.tsx
  used-libs.md
Labels: setup

#70 Add `TripSettings` screen
  .github/workflows/ci.yml
  .prettierrc.json
  App.tsx
  src/components/ActivityCard/ActivityCard.tsx
  src/components/ActivityGroupHeader.tsx
  src/components/ApolloConnection/ApolloConnection.tsx
  src/components/ScreenHeader.tsx
  src/components/SvgLogo.tsx
  src/components/TripCard/AvatarList.tsx
  src/components/TripCard/TripCard.tsx
  src/components/svg/SvgStrandedTraveller.tsx
  src/components/svg/SvgTravelPlan.tsx
  src/hooks/useCurrentAuthUser.tsx
  src/routes/TripHeaderContext.ts
  src/routes/TripTabs.tsx
  src/screens/AddEditActivityGroup/AddEditActivityGroupScreen.tsx
  src/screens/AddTrip/AddTrip.tsx
  src/screens/Itinerary/TripItinerary.tsx
  src/screens/Login/Login.tsx
  src/screens/Profile/Profile.tsx
  src/screens/Register/Register.tsx
  src/screens/ShareTrip/ShareTrip.tsx
  src/screens/TripSettings/TripSettings.tsx
  src/screens/TripSettings/get-trip.query.gql
  src/screens/TripSettings/leave-trip.mutation.gql
  src/screens/TripSettings/remove-member.mutation.gql
  src/screens/TripSettings/types/get-trip.query.ts
  src/screens/TripSettings/types/leave-trip.mutation.ts
  src/screens/TripSettings/types/remove-member.mutation.ts
  src/screens/TripSettings/types/update-trip.mutation.ts
  src/screens/TripSettings/update-trip.mutation.gql
  src/screens/TripsDashboard/TripsDashboard.tsx
  src/screens/ViewAddEditActivity/ViewAddEditActivity.tsx
  src/services/i18n.ts
  src/types/TripTabParamList.ts
Labels: initial app concept

#75 Implement missing share button functionality
  src/routes/TripTabs.tsx
  src/screens/ShareTrip/ShareTrip.tsx
  src/services/shareSheetHandler.ts
  src/types/TripTabParamList.ts
Labels: initial app concept

#76 Add `JoinTrip` screen
  .gitignore
  App.tsx
  app.json
  package-lock.json
  package.json
  src/graphql.schema.json
  src/screens/AddTrip/AddTrip.tsx
  src/screens/ShareTrip/ShareTrip.tsx
  src/screens/ShareTrip/get-invitation.query.gql
  src/screens/ShareTrip/get-trip.query.gql
  src/screens/ShareTrip/join-trip.mutation.gql
  src/screens/ShareTrip/types/get-invitation.query.ts
  src/screens/ShareTrip/types/get-trip.query.ts
  src/screens/ShareTrip/types/join-trip.mutation.ts
  src/services/i18n.ts
  src/services/shareSheetHandler.ts
  src/types.d.ts
  src/types/RootStackParamList.ts
  tsconfig.json
Labels: initial app concept

#89 Bug/86 header icon alignment
  src/components/ScreenHeader.tsx
  src/services/i18n.ts
Labels: bug

#90 add info to login and register
  src/screens/Login/Login.tsx
  src/screens/Register/Register.tsx
  src/services/i18n.ts
Labels: bug

#82 Update translation strings
  src/screens/AddEditActivityGroup/AddEditActivityGroupScreen.tsx
  src/screens/AddTrip/AddTrip.tsx
  src/screens/Login/Login.tsx
  src/screens/Profile/Profile.tsx
  src/screens/Register/Register.tsx
  src/screens/TripSettings/TripSettings.tsx
  src/services/i18n.ts
Labels: enhancement

#97 Add missing loading indicator in TripSettings screen
  src/screens/TripSettings/TripSettings.tsx
Labels: bug

#98 Fix wrong trip date handling
  src/components/TripCard/TripCard.tsx
  src/screens/TripsDashboard/TripsDashboard.tsx
Labels: bug

#99 changed from to planned at and styling
  src/screens/ViewAddEditActivity/ViewAddEditActivity.tsx
  src/services/i18n.ts
Labels: bug

#100 Feature/add trip dates to itinerary
  src/graphql.schema.json
  src/screens/Itinerary/TripItinerary.tsx
  src/screens/Itinerary/getTripQuery.gql
  src/screens/Itinerary/types/getTripQuery.ts
  src/types.d.ts
Labels: enhancement

#105 Standardize fonts, margins, styling
  src/components/ActivityGroup.tsx
  src/components/TripCard/TripCard.tsx
  src/screens/AddEditActivityGroup/AddEditActivityGroupScreen.tsx
  src/screens/AddTrip/AddTrip.tsx
  src/screens/Itinerary/TripItinerary.tsx
  src/screens/Login/Login.tsx
  src/screens/Profile/Profile.tsx
  src/screens/Register/Register.tsx
  src/screens/ShareTrip/ShareTrip.tsx
  src/screens/TripSettings/TripSettings.tsx
  src/screens/TripsDashboard/TripsDashboard.tsx
  src/screens/ViewAddEditActivity/ViewAddEditActivity.tsx
  src/services/i18n.ts
  src/theme/theme.ts
  used-libs.md
Labels: bug, enhancement
