Repository vacatius/mobile-app, pull requests merged in 2021-04, with the labels that each got.

#14 #12 i18n
  App.tsx
  package-lock.json
  package.json
  src/services/i18n.ts
  src/services/react-i18next.d.ts
Labels: enhancement, optional

#15 Implement Login screen without backend and storybook integration
  .expo-shared/assets.json
  .github/workflows/cd.yml
  .idea/prettier.xml
  .prettierignore
  .prettierrc.json
  App.tsx
  app.json
  babel.config.js
  package-lock.json
  package.json
  src/components/SvgLogo.tsx
  src/screens/Login.tsx
  src/screens/Register.tsx
  src/services/i18n.ts
  src/services/react-i18next.d.ts
  tsconfig.json
  used-libs.md
Labels: initial app concept

#18 Implement Trips Dashboard screen
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .prettierignore
  App.tsx
  babel.config.js
  codegen.yml
  package-lock.json
  package.json
  src/components/ScreenHeader.tsx
  src/components/TripCard/AvatarList.tsx
  src/components/TripCard/TripCard.tsx
  src/get-environment.ts
  src/graphql.schema.json
  src/screens/TripsDashboard/TripsDashboard.tsx
  src/screens/TripsDashboard/trip-dashboard.query.gql
  src/screens/TripsDashboard/types/trip-dashboard.query.ts
  src/services/i18n.ts
  src/types.d.ts
  src/types/env.d.ts
  used-libs.md
Labels: initial app concept

#20 Feature/login screen backend
  .env.example
  App.tsx
  package-lock.json
  package.json
  src/components/ApolloConnection/ApolloConnection.tsx
  src/components/ApolloConnection/refresh-token.mutation.ts
  src/components/ApolloConnection/types/refresh-token.mutation.ts
  src/graphql.schema.json
  src/hooks/useCurrentAuthUser.tsx
  src/screens/Login.tsx
  src/screens/Login/Login.tsx
  src/screens/Login/loginMutation.gql
  src/screens/Login/types/loginMutation.ts
  src/screens/Register.tsx
  src/screens/Register/Register.tsx
  src/screens/Register/registerMutation.gql
  src/screens/Register/types/registerMutation.ts
  src/screens/TripsDashboard/TripsDashboard.tsx
  src/services/i18n.ts
  src/types.d.ts
  src/types/RootStackParamList.ts
  src/types/SecureStorageItems.ts
  used-libs.md
Labels: initial app concept

#21 Add CI badge to README.MD
  README.MD
Labels: documentation

#24 Add Eslint to Project & CI Pipeline
  .eslintrc.js
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/components/ApolloConnection/ApolloConnection.tsx
  src/components/ScreenHeader.tsx
  src/components/TripCard/AvatarList.tsx
  src/components/TripCard/TripCard.tsx
  src/get-environment.ts
  src/screens/Login/Login.tsx
  src/screens/Login/types/loginMutation.ts
  src/screens/Register/Register.tsx
  src/screens/Register/types/registerMutation.ts
  src/screens/TripsDashboard/TripsDashboard.tsx
  src/services/react-i18next.d.ts
  src/types/env.d.ts
Labels: enhancement

#25 Enforce LF in gitattributes
  .gitattributes
Labels: enhancement

#27 Add Trip Screen (#6)
  App.tsx
  src/components/TripCard/TripCard.tsx
  src/screens/AddTrip/AddTrip.tsx
  src/screens/AddTrip/add-trip.mutation.gql
  src/screens/AddTrip/types/add-trip.mutation.ts
  src/screens/TripsDashboard/TripsDashboard.tsx
  src/services/i18n.ts
Labels: initial app concept

#30 Implement ShareTrip screen
  .env.example
  App.tsx
  app.json
  package.json
  src/components/ScreenHeader.tsx
  src/get-environment.ts
  src/graphql.schema.json
  src/screens/AddTrip/AddTrip.tsx
  src/screens/ShareTrip/ShareTrip.tsx
  src/screens/ShareTrip/create-invite.mutation.gql
  src/screens/ShareTrip/types/create-invite.mutation.ts
  src/services/i18n.ts
  src/types.d.ts
  src/types/RootStackParamList.ts
  src/types/env.d.ts
Labels: initial app concept

#39 Implement TripItinerary screen
  .eslintrc.js
  App.tsx
  package-lock.json
  src/components/ActivityCard/ActivityCard.tsx
  src/components/ActivityCard/CreateActivityReactionMutation.gql
  src/components/ActivityCard/RemoveActivityReactionMutation.gql
  src/components/ActivityCard/UpdateActivityReactionMutation.gql
  src/components/ActivityCard/types/CreateActivityReactionMutation.ts
  src/components/ActivityCard/types/RemoveActivityReactionMutation.ts
  src/components/ActivityCard/types/UpdateActivityReactionMutation.ts
  src/components/ActivityGroup.tsx
  src/components/ActivityGroupHeader.tsx
  src/hooks/useCurrentAuthUser.tsx
  src/screens/AddTrip/AddTrip.tsx
  src/screens/Itinerary/TripItinerary.tsx
  src/screens/Itinerary/getTripQuery.gql
  src/screens/Itinerary/types/getTripQuery.ts
  src/screens/Login/types/loginMutation.ts
  src/screens/Register/types/registerMutation.ts
  src/screens/ShareTrip/ShareTrip.tsx
  src/screens/TripsDashboard/TripsDashboard.tsx
  src/services/i18n.ts
  src/types/RootStackParamList.ts
  used-libs.md
Labels: initial app concept

#42 Add global routes enum
  App.tsx
  src/screens/AddTrip/AddTrip.tsx
  src/screens/Itinerary/TripItinerary.tsx
  src/screens/Login/Login.tsx
  src/screens/Register/Register.tsx
  src/screens/ShareTrip/ShareTrip.tsx
  src/screens/TripsDashboard/TripsDashboard.tsx
  src/types/Routes.ts
Labels: enhancement

#43 Fix styling, linting, return types
  .eslintrc.js
  .gitattributes
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .prettierignore
  App.tsx
  package-lock.json
  package.json
  src/components/ActivityCard/ActivityCard.tsx
  src/components/ActivityGroup.tsx
  src/components/ActivityGroupHeader.tsx
  src/components/ApolloConnection/ApolloConnection.tsx
  src/components/SvgLogo.tsx
  src/get-environment.ts
  src/hooks/useCurrentAuthUser.tsx
  src/screens/AddTrip/AddTrip.tsx
  src/screens/Itinerary/TripItinerary.tsx
  src/screens/Login/Login.tsx
  src/screens/Register/Register.tsx
  src/screens/ShareTrip/ShareTrip.tsx
  src/screens/TripsDashboard/TripsDashboard.tsx
  src/services/i18n.ts
  src/services/react-i18next.d.ts
  used-libs.md
Labels: enhancement

#44 make avatar color unique
  package-lock.json
  package.json
  src/components/TripCard/AvatarList.tsx
Labels: enhancement

#51 Feature/19 central screen header
  App.tsx
  src/components/ScreenHeader.tsx
  src/screens/Itinerary/TripItinerary.tsx
  src/screens/TripsDashboard/TripsDashboard.tsx
Labels: enhancement

#52 fix: Cannot update a component from inside the function body of a different component
  src/screens/Itinerary/TripItinerary.tsx
Labels: bug

#53 User friendly error handling, make accordion header pressable, optical fixes
  App.tsx
  package-lock.json
  package.json
  src/components/ActivityGroupHeader.tsx
  src/components/ApolloConnection/ApolloConnection.tsx
  src/screens/AddEditActivityGroup/AddEditActivityGroupScreen.tsx
  used-libs.md
Labels: enhancement
